# [[main]]
#   weight = 1
#   identifier = "posts"
#   name = "Posts"
#   url = "/posts/"

# [[main]]
#   weight = 2
#   identifier = "tags"
#   name = "Tags"
#   url = "/tags/"

# [[main]]
#   weight = 3
#   identifier = "categories"
#   name = "Categories"
#   url = "/categories/"

[[main]]
  weight = 1
  identifier = "about"
  name = "About"
  url = "/about/"
